### PR TITLE
PR for Issue #8: Added output for internet gateway

### PR DESCRIPTION
**Pull request by difu**
Signed-off-by: Dirk Fuchs <difu@mac.com>

### CODE REVIEW

**Comment by markxnelson** [comment]
Thank you for your contribution.  Please note that we can only merge PR's from signatories of the Oracle Contribution Agreement.  Please see our CONTRIBUTING.md for more information.

**Comment by difu** [comment]
> Thank you for your contribution. Please note that we can only merge PR's from signatories of the Oracle Contribution Agreement. Please see our CONTRIBUTING.md for more information.

Hi, could you kindly describe what I missed? This change adds an output. I was not able to find any docs on existing outputs that could have been extended.

**Comment by markxnelson** [comment]
Yes, we can only accept PR's from people who have signed the Oracle Contribution Agreement.  There is a link to that in the CONTRIBUTING.md.  Here is a direct link: https://www.oracle.com/technical-resources/oracle-contributor-agreement.html 
I cannot merge/accept your PR unless you sign that agreement.  Since this is such a small change, if you prefer not to sign the agreement, I am pretty sure I could go and implement a fix for your issue independently for you.

**Comment by difu** [comment]
Thanks for clarification! I sent my OCA. 
Cheers Dirk

**Comment by markxnelson** [comment]
Thanks. I will check for the approval, and then i can merge this. Thanks again for contributing!

**Pull request merged**
